import { DispatchLoad, CarrierProfile, ShipperProfile, DocumentScanResult, AccountingTransaction } from '@/types/tms';

export const initialMockLoads: DispatchLoad[] = [
  {
    id: 'ld_101',
    loadNumber: 'FF-88902',
    shipper: {
      id: 'shp_1',
      name: 'Apex Cold Foods Logistics',
      contact: 'Sarah Jenkins',
      phone: '+1 (312) 555-0143',
      email: 'logistics@apexfoods.com',
      creditLimit: 150000,
      availableCredit: 112450,
      paymentTerms: 'Net 30',
    },
    carrier: {
      id: 'car_1',
      name: 'Titan Freight Lines LLC',
      mcNumber: '1049281',
      dotNumber: '3291044',
      driverName: 'Marcus Vance',
      driverPhone: '+1 (214) 555-0199',
      truckNumber: 'TK-402',
      trailerNumber: 'TR-9881',
      safetyRating: 'Satisfactory',
      insuranceExpiry: '2026-11-15',
      coiVerified: true,
      factoringCompany: 'TriumphPay Financial',
    },
    equipment: 'reefer',
    status: 'in_transit',
    stops: [
      {
        id: 'st_101',
        type: 'pickup',
        sequence: 1,
        facility: 'DFW Cold Storage Hub #4',
        address: '8400 Logistics Pkwy',
        city: 'Dallas',
        state: 'TX',
        zip: '75201',
        date: '2026-08-20',
        timeWindow: '08:00 - 11:30',
        contactName: 'Dave Miller',
        contactPhone: '+1 (214) 555-8812',
        specialInstructions: 'Pre-cool trailer to -10°F. Seal verified on BOL.',
        completedAt: '2026-08-20T10:45:00Z',
        status: 'departed',
      },
      {
        id: 'st_102',
        type: 'delivery',
        sequence: 2,
        facility: 'Kroger Distribution Center #12',
        address: '4200 Interstate Blvd',
        city: 'Atlanta',
        state: 'GA',
        zip: '30301',
        date: '2026-08-23',
        timeWindow: '06:00 - 10:00',
        contactName: 'Receiving Dock A',
        contactPhone: '+1 (404) 555-9021',
        specialInstructions: 'Lumper required ($185 pre-authorized). Temperature printout required.',
        status: 'pending',
      },
    ],
    financials: {
      shipperRate: 3850.00,
      carrierRate: 3100.00,
      fuelSurcharge: 420.00,
      accessorials: 0,
      lumperFee: 185.00,
      detention: 0,
      margin: 750.00,
      marginPercent: 19.48,
    },
    miles: 782,
    rpm: 4.92,
    commodity: 'Frozen Organic Berries & Bakery',
    weightLbs: 42500,
    temperature: '-10°F Continuous',
    sealNumber: 'SL-994821',
    bolNumber: 'BOL-APX-88902',
    trackingActive: true,
    trackingToken: 'trk_marcus_vance_88902',
    rateConSigned: true,
    rateConSignedAt: '2026-08-19T14:22:10Z',
    rateConSignerName: 'Marcus Vance (Driver)',
    driverLocation: {
      lat: 32.7767,
      lng: -89.6012,
      city: 'Jackson',
      state: 'MS',
      lastUpdated: '8 mins ago',
      speedMph: 64,
    },
    documents: [
      { id: 'doc_1', name: 'Rate_Confirmation_FF88902_Signed.pdf', type: 'rate_con', uploadedAt: '2026-08-19', fileSize: '240 KB', verified: true },
      { id: 'doc_2', name: 'BOL_Pickup_Signed_DFW.pdf', type: 'bol', uploadedAt: '2026-08-20', fileSize: '1.2 MB', verified: true },
    ],
    createdAt: '2026-08-19T09:00:00Z',
    updatedAt: '2026-08-22T08:15:00Z',
  },
  {
    id: 'ld_102',
    loadNumber: 'FF-88903',
    shipper: {
      id: 'shp_2',
      name: 'Vanguard Industrial Steels',
      contact: 'Robert Chen',
      phone: '+1 (219) 555-8822',
      email: 'dispatch@vanguardsteel.com',
      creditLimit: 250000,
      availableCredit: 198000,
      paymentTerms: 'Net 15',
    },
    carrier: null,
    equipment: 'flatbed',
    status: 'available',
    stops: [
      {
        id: 'st_103',
        type: 'pickup',
        sequence: 1,
        facility: 'Midwest Steel Coil Mill',
        address: '1200 Lakefront Way',
        city: 'Gary',
        state: 'IN',
        zip: '46401',
        date: '2026-08-23',
        timeWindow: '07:00 - 15:00',
        contactName: 'Shipping Gate 3',
        specialInstructions: '8ft drop tarps mandatory. Hard hat & safety vest required.',
        status: 'pending',
      },
      {
        id: 'st_104',
        type: 'delivery',
        sequence: 2,
        facility: 'AeroStructure Manufacturing',
        address: '900 Aviation Dr',
        city: 'Wichita',
        state: 'KS',
        zip: '67201',
        date: '2026-08-24',
        timeWindow: '08:00 - 13:00',
        contactName: 'Jim Caldwell',
        specialInstructions: 'Overhead crane offload. Clean dry coils.',
        status: 'pending',
      },
    ],
    financials: {
      shipperRate: 2650.00,
      carrierRate: 2050.00,
      fuelSurcharge: 280.00,
      accessorials: 150.00,
      lumperFee: 0,
      detention: 0,
      margin: 600.00,
      marginPercent: 22.64,
    },
    miles: 598,
    rpm: 4.43,
    commodity: 'Structural Steel Coils',
    weightLbs: 46800,
    bolNumber: 'BOL-VIS-7718',
    trackingActive: false,
    trackingToken: 'trk_pending_flatbed_88903',
    rateConSigned: false,
    documents: [],
    createdAt: '2026-08-21T11:30:00Z',
    updatedAt: '2026-08-22T06:00:00Z',
  },
  {
    id: 'ld_103',
    loadNumber: 'FF-88904',
    shipper: {
      id: 'shp_3',
      name: 'OmniPack Consumer Goods',
      contact: 'Jessica Morales',
      phone: '+1 (614) 555-7731',
      email: 'jessica@omnipack.com',
      creditLimit: 100000,
      availableCredit: 42000,
      paymentTerms: 'Net 30',
    },
    carrier: {
      id: 'car_2',
      name: 'Blue Star Transport Corp',
      mcNumber: '892110',
      dotNumber: '2810931',
      driverName: 'Sergei Morozov',
      driverPhone: '+1 (312) 555-9923',
      truckNumber: 'BST-19',
      trailerNumber: 'TR-5321',
      safetyRating: 'Satisfactory',
      insuranceExpiry: '2026-10-01',
      coiVerified: true,
      factoringCompany: 'Apex Capital Corp',
    },
    equipment: 'dry_van',
    status: 'delivered',
    stops: [
      {
        id: 'st_105',
        type: 'pickup',
        sequence: 1,
        facility: 'OmniPack Fulfillment Plant #1',
        address: '500 Commerce Way',
        city: 'Columbus',
        state: 'OH',
        zip: '43201',
        date: '2026-08-19',
        timeWindow: '09:00 - 14:00',
        completedAt: '2026-08-19T13:10:00Z',
        status: 'departed',
      },
      {
        id: 'st_106',
        type: 'delivery',
        sequence: 2,
        facility: 'Target Regional DC #58',
        address: '7700 Logistics Way',
        city: 'Charlotte',
        state: 'NC',
        zip: '28201',
        date: '2026-08-21',
        timeWindow: '07:00 - 11:00',
        completedAt: '2026-08-21T08:30:00Z',
        status: 'departed',
      },
    ],
    financials: {
      shipperRate: 2150.00,
      carrierRate: 1750.00,
      fuelSurcharge: 210.00,
      accessorials: 0,
      lumperFee: 0,
      detention: 0,
      margin: 400.00,
      marginPercent: 18.60,
    },
    miles: 432,
    rpm: 4.98,
    commodity: 'Packaged Household Paper Goods',
    weightLbs: 28400,
    sealNumber: 'SL-88310',
    bolNumber: 'BOL-OMN-4421',
    trackingActive: false,
    trackingToken: 'trk_sergei_delivered_88904',
    rateConSigned: true,
    rateConSignedAt: '2026-08-18T16:45:00Z',
    rateConSignerName: 'Sergei Morozov',
    documents: [
      { id: 'doc_3', name: 'Rate_Confirmation_FF88904.pdf', type: 'rate_con', uploadedAt: '2026-08-18', fileSize: '210 KB', verified: true },
      { id: 'doc_4', name: 'Signed_POD_Target_DC.pdf', type: 'pod', uploadedAt: '2026-08-21', fileSize: '850 KB', verified: true },
    ],
    createdAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-08-21T09:00:00Z',
  },
  {
    id: 'ld_104',
    loadNumber: 'FF-88905',
    shipper: {
      id: 'shp_4',
      name: 'Sunbelt Agri-Products Inc',
      contact: 'Danielle Brooks',
      phone: '+1 (813) 555-9011',
      email: 'shipping@sunbeltagri.com',
      creditLimit: 80000,
      availableCredit: 62000,
      paymentTerms: 'Net 30',
    },
    carrier: {
      id: 'car_3',
      name: 'Eagle Express Hauling',
      mcNumber: '761920',
      dotNumber: '2190841',
      driverName: 'Carlos Ramirez',
      driverPhone: '+1 (407) 555-4491',
      truckNumber: 'EE-104',
      trailerNumber: 'TR-771',
      safetyRating: 'Satisfactory',
      insuranceExpiry: '2026-09-10',
      coiVerified: true,
    },
    equipment: 'reefer',
    status: 'dispatched',
    stops: [
      {
        id: 'st_107',
        type: 'pickup',
        sequence: 1,
        facility: 'Sunbelt Citrus Packing Facility',
        address: '1400 Citrus Blossom Rd',
        city: 'Orlando',
        state: 'FL',
        zip: '32801',
        date: '2026-08-22',
        timeWindow: '14:00 - 18:00',
        specialInstructions: 'Continuous +36°F. Pulp fruit prior to loading.',
        status: 'pending',
      },
      {
        id: 'st_108',
        type: 'delivery',
        sequence: 2,
        facility: 'Hunt Point Terminal Market',
        address: '772 Food Center Dr',
        city: 'Bronx',
        state: 'NY',
        zip: '10474',
        date: '2026-08-24',
        timeWindow: '04:00 - 08:00',
        specialInstructions: 'Night offload. Driver assist authorized.',
        status: 'pending',
      },
    ],
    financials: {
      shipperRate: 4400.00,
      carrierRate: 3600.00,
      fuelSurcharge: 510.00,
      accessorials: 200.00,
      lumperFee: 0,
      detention: 0,
      margin: 800.00,
      marginPercent: 18.18,
    },
    miles: 1080,
    rpm: 4.07,
    commodity: 'Fresh Florida Oranges (Palletized)',
    weightLbs: 41200,
    temperature: '+36°F Continuous',
    bolNumber: 'BOL-SBT-9901',
    trackingActive: true,
    trackingToken: 'trk_carlos_ramirez_88905',
    rateConSigned: true,
    rateConSignedAt: '2026-08-22T08:00:00Z',
    rateConSignerName: 'Carlos Ramirez',
    driverLocation: {
      lat: 28.5383,
      lng: -81.3792,
      city: 'Orlando',
      state: 'FL',
      lastUpdated: '15 mins ago',
      speedMph: 0,
    },
    documents: [
      { id: 'doc_5', name: 'Rate_Confirmation_FF88905.pdf', type: 'rate_con', uploadedAt: '2026-08-22', fileSize: '215 KB', verified: true },
    ],
    createdAt: '2026-08-21T16:00:00Z',
    updatedAt: '2026-08-22T08:00:00Z',
  },
  {
    id: 'ld_105',
    loadNumber: 'FF-88906',
    shipper: {
      id: 'shp_5',
      name: 'Cascadia Beverage Bottlers',
      contact: 'Alan Foster',
      phone: '+1 (503) 555-3211',
      email: 'alan@cascadiabev.com',
      creditLimit: 120000,
      availableCredit: 94000,
      paymentTerms: 'Net 30',
    },
    carrier: {
      id: 'car_4',
      name: 'Pacific Freightline Express',
      mcNumber: '654321',
      dotNumber: '1987654',
      driverName: 'Tyrone Washington',
      driverPhone: '+1 (206) 555-8819',
      truckNumber: 'PFE-88',
      trailerNumber: 'TR-1029',
      safetyRating: 'Satisfactory',
      insuranceExpiry: '2026-12-31',
      coiVerified: true,
    },
    equipment: 'dry_van',
    status: 'invoiced',
    stops: [
      {
        id: 'st_109',
        type: 'pickup',
        sequence: 1,
        facility: 'Cascadia Bottling Plant #2',
        address: '990 Industrial Blvd',
        city: 'Portland',
        state: 'OR',
        zip: '97201',
        date: '2026-08-15',
        timeWindow: '08:00 - 12:00',
        completedAt: '2026-08-15T11:00:00Z',
        status: 'departed',
      },
      {
        id: 'st_110',
        type: 'delivery',
        sequence: 2,
        facility: 'Costco Wholesale Regional Depot',
        address: '1500 Distribution Way',
        city: 'Salt Lake City',
        state: 'UT',
        zip: '84101',
        date: '2026-08-17',
        timeWindow: '07:00 - 11:00',
        completedAt: '2026-08-17T09:45:00Z',
        status: 'departed',
      },
    ],
    financials: {
      shipperRate: 3100.00,
      carrierRate: 2500.00,
      fuelSurcharge: 320.00,
      accessorials: 0,
      lumperFee: 0,
      detention: 0,
      margin: 600.00,
      marginPercent: 19.35,
    },
    miles: 765,
    rpm: 4.05,
    commodity: 'Sparkling Artesian Water (Canned)',
    weightLbs: 43800,
    bolNumber: 'BOL-CBB-1102',
    trackingActive: false,
    trackingToken: 'trk_tyrone_invoiced_88906',
    rateConSigned: true,
    rateConSignedAt: '2026-08-14T15:00:00Z',
    rateConSignerName: 'Tyrone Washington',
    documents: [
      { id: 'doc_6', name: 'Rate_Confirmation_FF88906.pdf', type: 'rate_con', uploadedAt: '2026-08-14', fileSize: '210 KB', verified: true },
      { id: 'doc_7', name: 'POD_Costco_SLC.pdf', type: 'pod', uploadedAt: '2026-08-17', fileSize: '910 KB', verified: true },
      { id: 'doc_8', name: 'Invoice_INV-2026-88906.pdf', type: 'carrier_invoice', uploadedAt: '2026-08-18', fileSize: '180 KB', verified: true },
    ],
    createdAt: '2026-08-14T09:00:00Z',
    updatedAt: '2026-08-18T10:00:00Z',
  },
];

export const initialMockCarriers: CarrierProfile[] = [
  {
    id: 'car_1',
    name: 'Titan Freight Lines LLC',
    mcNumber: '1049281',
    dotNumber: '3291044',
    contactName: 'Elena Rostova',
    phone: '+1 (214) 555-0199',
    email: 'dispatch@titanfreight.com',
    address: '4500 Express Way, Suite 300',
    city: 'Dallas',
    state: 'TX',
    zip: '75247',
    status: 'active',
    safetyRating: 'Satisfactory',
    safetyScore: 94,
    insuranceCompany: 'Progressive Commercial Insurance',
    insurancePolicyNumber: 'PC-99418290-A',
    insuranceCoverageAmount: 1000000,
    insuranceExpiration: '2026-11-15',
    daysToInsuranceExpiry: 85,
    w9Verified: true,
    coiVerified: true,
    authorityActive: true,
    equipmentFleet: ['reefer', 'dry_van'],
    totalLoadsCompleted: 148,
    onTimeDeliveryRate: 98.6,
    averageRatePerMile: 2.85,
    factoringCompany: 'TriumphPay Financial',
    factoringEmail: 'notices@triumphpay.com',
    notes: 'Tier 1 preferred carrier. Dedicated reefer team drivers for cross-country runs.',
    createdAt: '2025-02-10',
  },
  {
    id: 'car_2',
    name: 'Blue Star Transport Corp',
    mcNumber: '892110',
    dotNumber: '2810931',
    contactName: 'Oleg Morozov',
    phone: '+1 (312) 555-9923',
    email: 'ops@bluestartransport.com',
    address: '8800 S Pulaski Rd',
    city: 'Chicago',
    state: 'IL',
    zip: '60652',
    status: 'active',
    safetyRating: 'Satisfactory',
    safetyScore: 91,
    insuranceCompany: 'Great West Casualty Co',
    insurancePolicyNumber: 'GW-881920-B',
    insuranceCoverageAmount: 1000000,
    insuranceExpiration: '2026-10-01',
    daysToInsuranceExpiry: 40,
    w9Verified: true,
    coiVerified: true,
    authorityActive: true,
    equipmentFleet: ['dry_van', 'flatbed'],
    totalLoadsCompleted: 92,
    onTimeDeliveryRate: 96.7,
    averageRatePerMile: 2.45,
    factoringCompany: 'Apex Capital Corp',
    factoringEmail: 'assign@apexcapitalcorp.com',
    notes: 'Strong Midwest to East Coast corridor lanes.',
    createdAt: '2025-05-18',
  },
  {
    id: 'car_3',
    name: 'Eagle Express Hauling',
    mcNumber: '761920',
    dotNumber: '2190841',
    contactName: 'Carlos Ramirez',
    phone: '+1 (407) 555-4491',
    email: 'carlos@eagleexpressfl.com',
    address: '2200 Orange Blossom Trail',
    city: 'Orlando',
    state: 'FL',
    zip: '32805',
    status: 'active',
    safetyRating: 'Satisfactory',
    safetyScore: 88,
    insuranceCompany: 'Northland Insurance',
    insurancePolicyNumber: 'NL-449019-1',
    insuranceCoverageAmount: 1000000,
    insuranceExpiration: '2026-09-08',
    daysToInsuranceExpiry: 17, // Expiring soon!
    w9Verified: true,
    coiVerified: true,
    authorityActive: true,
    equipmentFleet: ['reefer'],
    totalLoadsCompleted: 64,
    onTimeDeliveryRate: 94.2,
    averageRatePerMile: 3.10,
    notes: 'WARNING: Insurance renewal due in 17 days. Automated notice sent.',
    createdAt: '2025-08-01',
  },
  {
    id: 'car_4',
    name: 'Pacific Freightline Express',
    mcNumber: '654321',
    dotNumber: '1987654',
    contactName: 'Tyrone Washington',
    phone: '+1 (206) 555-8819',
    email: 'tyrone@pacificfreightline.com',
    address: '100 Rainier Ave S',
    city: 'Seattle',
    state: 'WA',
    zip: '98144',
    status: 'active',
    safetyRating: 'Satisfactory',
    safetyScore: 96,
    insuranceCompany: 'Travelers Commercial',
    insurancePolicyNumber: 'TRV-9901842',
    insuranceCoverageAmount: 1500000,
    insuranceExpiration: '2026-12-31',
    daysToInsuranceExpiry: 131,
    w9Verified: true,
    coiVerified: true,
    authorityActive: true,
    equipmentFleet: ['dry_van', 'step_deck'],
    totalLoadsCompleted: 110,
    onTimeDeliveryRate: 99.1,
    averageRatePerMile: 2.75,
    notes: 'Top performer on I-5 West Coast freight.',
    createdAt: '2025-01-15',
  },
  {
    id: 'car_5',
    name: 'Redline Logistics Inc',
    mcNumber: '449102',
    dotNumber: '1655019',
    contactName: 'Brian Kowalski',
    phone: '+1 (313) 555-6671',
    email: 'brian@redlinemichigan.com',
    address: '400 Michigan Ave',
    city: 'Detroit',
    state: 'MI',
    zip: '48226',
    status: 'pending_review',
    safetyRating: 'Conditional',
    safetyScore: 72,
    insuranceCompany: 'Canal Insurance',
    insurancePolicyNumber: 'CN-102931',
    insuranceCoverageAmount: 750000,
    insuranceExpiration: '2026-08-30',
    daysToInsuranceExpiry: 8,
    w9Verified: true,
    coiVerified: false,
    authorityActive: true,
    equipmentFleet: ['flatbed'],
    totalLoadsCompleted: 14,
    onTimeDeliveryRate: 85.7,
    averageRatePerMile: 2.90,
    notes: 'Conditional rating due to HOS inspection audit. Needs management override to dispatch.',
    createdAt: '2026-06-10',
  },
];

export const initialMockShippers: ShipperProfile[] = [
  {
    id: 'shp_1',
    name: 'Apex Cold Foods Logistics',
    accountNumber: 'ACT-APX-01',
    contactName: 'Sarah Jenkins (VP Supply Chain)',
    phone: '+1 (312) 555-0143',
    email: 'logistics@apexfoods.com',
    billingAddress: '500 W Madison St, Suite 2200',
    city: 'Chicago',
    state: 'IL',
    zip: '60661',
    creditScore: 92,
    creditLimit: 150000,
    availableCredit: 112450,
    paymentTerms: 'Net 30',
    status: 'active',
    totalLoadsBooked: 342,
    mtdVolume: 48900,
    ytdVolume: 492000,
    primaryCommodity: 'Refrigerated & Frozen Foods',
    rating: 4.9,
    notes: 'Key enterprise shipper. 48-hour tender lead time on regular reefer lanes.',
    createdAt: '2024-11-01',
  },
  {
    id: 'shp_2',
    name: 'Vanguard Industrial Steels',
    accountNumber: 'ACT-VIS-02',
    contactName: 'Robert Chen (Logistics Director)',
    phone: '+1 (219) 555-8822',
    email: 'dispatch@vanguardsteel.com',
    billingAddress: '1200 Lakefront Industrial Way',
    city: 'Gary',
    state: 'IN',
    zip: '46401',
    creditScore: 88,
    creditLimit: 250000,
    availableCredit: 198000,
    paymentTerms: 'Net 15',
    status: 'active',
    totalLoadsBooked: 215,
    mtdVolume: 32400,
    ytdVolume: 380000,
    primaryCommodity: 'Steel Coils, Plates & Beams',
    rating: 4.8,
    notes: 'Excellent payer, consistent flatbed freight. Requires heavy-duty equipment.',
    createdAt: '2025-01-20',
  },
  {
    id: 'shp_3',
    name: 'OmniPack Consumer Goods',
    accountNumber: 'ACT-OMN-03',
    contactName: 'Jessica Morales (Freight Coordinator)',
    phone: '+1 (614) 555-7731',
    email: 'jessica@omnipack.com',
    billingAddress: '8800 Polaris Pkwy',
    city: 'Columbus',
    state: 'OH',
    zip: '43240',
    creditScore: 78,
    creditLimit: 100000,
    availableCredit: 42000,
    paymentTerms: 'Net 30',
    status: 'active',
    totalLoadsBooked: 180,
    mtdVolume: 22100,
    ytdVolume: 260000,
    primaryCommodity: 'Household Paper & CPG',
    rating: 4.6,
    notes: 'High volume dry van freight out of Ohio and Pennsylvania DCs.',
    createdAt: '2025-03-12',
  },
  {
    id: 'shp_4',
    name: 'Sunbelt Agri-Products Inc',
    accountNumber: 'ACT-SBT-04',
    contactName: 'Danielle Brooks',
    phone: '+1 (813) 555-9011',
    email: 'shipping@sunbeltagri.com',
    billingAddress: '400 S Ashley Dr',
    city: 'Tampa',
    state: 'FL',
    zip: '33602',
    creditScore: 84,
    creditLimit: 80000,
    availableCredit: 62000,
    paymentTerms: 'Net 30',
    status: 'active',
    totalLoadsBooked: 95,
    mtdVolume: 18400,
    ytdVolume: 145000,
    primaryCommodity: 'Citrus & Tropical Produce',
    rating: 4.7,
    notes: 'Seasonal surges March-August. Fast loading docks.',
    createdAt: '2025-06-05',
  },
  {
    id: 'shp_5',
    name: 'Cascadia Beverage Bottlers',
    accountNumber: 'ACT-CBB-05',
    contactName: 'Alan Foster',
    phone: '+1 (503) 555-3211',
    email: 'alan@cascadiabev.com',
    billingAddress: '1100 NW 14th Ave',
    city: 'Portland',
    state: 'OR',
    zip: '97209',
    creditScore: 90,
    creditLimit: 120000,
    availableCredit: 94000,
    paymentTerms: 'Net 30',
    status: 'active',
    totalLoadsBooked: 160,
    mtdVolume: 29000,
    ytdVolume: 310000,
    primaryCommodity: 'Canned Beverages & Syrups',
    rating: 4.9,
    notes: 'Heavy weight shipments (43-44k lbs). Require clean food-grade trailers.',
    createdAt: '2025-02-28',
  },
];

export const initialMockDocuments: DocumentScanResult[] = [
  {
    id: 'ocr_doc_1',
    fileName: 'Rate_Confirmation_Titan_FF88902.pdf',
    fileType: 'rate_con',
    fileSize: '340 KB',
    uploadDate: '2026-08-22T08:30:00Z',
    status: 'verified',
    confidenceScore: 98.4,
    extractedFields: {
      loadNumber: 'FF-88902',
      carrierName: 'Titan Freight Lines LLC',
      shipperName: 'Apex Cold Foods Logistics',
      originCity: 'Dallas',
      originState: 'TX',
      destCity: 'Atlanta',
      destState: 'GA',
      deliveryDate: '2026-08-23',
      linehaulAmount: 3100.00,
      fuelSurcharge: 420.00,
      accessorials: 0,
      totalAmount: 3520.00,
      weight: 42500,
      signeeName: 'Marcus Vance',
    },
    validationAlerts: [
      { type: 'success', message: 'All mandatory fields extracted with >95% AI confidence.' },
      { type: 'success', message: 'Carrier MC# 1049281 matched active profile in database.' },
    ],
    previewUrl: '/sample_docs/rate_con_sample.png',
  },
  {
    id: 'ocr_doc_2',
    fileName: 'Bill_Of_Lading_DFW_ColdHub.pdf',
    fileType: 'bol',
    fileSize: '1.4 MB',
    uploadDate: '2026-08-21T16:15:00Z',
    status: 'verified',
    confidenceScore: 96.8,
    extractedFields: {
      loadNumber: 'FF-88902',
      bolNumber: 'BOL-APX-88902',
      shipperName: 'Apex Cold Foods Logistics',
      originCity: 'Dallas',
      originState: 'TX',
      destCity: 'Atlanta',
      destState: 'GA',
      weight: 42500,
      pieceCount: 24,
      signeeName: 'Dave Miller (Shipper Agent)',
    },
    validationAlerts: [
      { type: 'success', message: 'Shipper signature & temperature stamp detected (-10°F).' },
    ],
    previewUrl: '/sample_docs/bol_sample.png',
  },
  {
    id: 'ocr_doc_3',
    fileName: 'Carrier_Invoice_BlueStar_88904.pdf',
    fileType: 'carrier_invoice',
    fileSize: '280 KB',
    uploadDate: '2026-08-22T07:45:00Z',
    status: 'needs_review',
    confidenceScore: 89.2,
    extractedFields: {
      invoiceNumber: 'INV-BST-9941',
      loadNumber: 'FF-88904',
      carrierName: 'Blue Star Transport Corp',
      linehaulAmount: 1750.00,
      accessorials: 150.00, // Detention claimed
      totalAmount: 1900.00,
      deliveryDate: '2026-08-21',
    },
    validationAlerts: [
      { type: 'warning', message: 'Carrier included $150 detention fee not present in original Rate Con.' },
      { type: 'warning', message: 'Detention timesheet requires broker approval before payment.' },
    ],
    previewUrl: '/sample_docs/invoice_sample.png',
  },
];

export const initialMockAccounting: AccountingTransaction[] = [
  {
    id: 'tx_ar_1',
    type: 'receivable',
    referenceNumber: 'INV-2026-88906',
    loadNumber: 'FF-88906',
    partyName: 'Cascadia Beverage Bottlers',
    issueDate: '2026-08-18',
    dueDate: '2026-09-17',
    amount: 3100.00,
    paidAmount: 0,
    balanceDue: 3100.00,
    status: 'pending',
    agingBucket: 'Current',
  },
  {
    id: 'tx_ar_2',
    type: 'receivable',
    referenceNumber: 'INV-2026-88904',
    loadNumber: 'FF-88904',
    partyName: 'OmniPack Consumer Goods',
    issueDate: '2026-08-21',
    dueDate: '2026-09-20',
    amount: 2150.00,
    paidAmount: 0,
    balanceDue: 2150.00,
    status: 'pending',
    agingBucket: 'Current',
  },
  {
    id: 'tx_ar_3',
    type: 'receivable',
    referenceNumber: 'INV-2026-88740',
    loadNumber: 'FF-88740',
    partyName: 'Apex Cold Foods Logistics',
    issueDate: '2026-07-15',
    dueDate: '2026-08-14',
    amount: 4200.00,
    paidAmount: 4200.00,
    balanceDue: 0.00,
    status: 'paid',
    agingBucket: 'Current',
    paymentMethod: 'ACH Direct Deposit',
    paymentReference: 'ACH-88910482',
  },
  {
    id: 'tx_ar_4',
    type: 'receivable',
    referenceNumber: 'INV-2026-88610',
    loadNumber: 'FF-88610',
    partyName: 'Vanguard Industrial Steels',
    issueDate: '2026-06-28',
    dueDate: '2026-07-28',
    amount: 3800.00,
    paidAmount: 0,
    balanceDue: 3800.00,
    status: 'overdue',
    agingBucket: '1-30 Days',
  },
  {
    id: 'tx_ap_1',
    type: 'payable',
    referenceNumber: 'SET-2026-88906',
    loadNumber: 'FF-88906',
    partyName: 'Pacific Freightline Express (MC 654321)',
    issueDate: '2026-08-18',
    dueDate: '2026-09-02',
    amount: 2500.00,
    paidAmount: 0,
    balanceDue: 2500.00,
    status: 'pending',
    agingBucket: 'Current',
    factoringBatchId: 'BATCH-AP-2026-34',
  },
  {
    id: 'tx_ap_2',
    type: 'payable',
    referenceNumber: 'SET-2026-88904',
    loadNumber: 'FF-88904',
    partyName: 'Blue Star Transport (MC 892110)',
    issueDate: '2026-08-21',
    dueDate: '2026-09-05',
    amount: 1750.00,
    paidAmount: 0,
    balanceDue: 1750.00,
    status: 'pending',
    agingBucket: 'Current',
    factoringBatchId: 'BATCH-AP-2026-34',
  },
  {
    id: 'tx_ap_3',
    type: 'payable',
    referenceNumber: 'SET-2026-88740',
    loadNumber: 'FF-88740',
    partyName: 'Titan Freight Lines LLC (MC 1049281)',
    issueDate: '2026-07-16',
    dueDate: '2026-07-30',
    amount: 3400.00,
    paidAmount: 3400.00,
    balanceDue: 0.00,
    status: 'paid',
    agingBucket: 'Current',
    paymentMethod: 'TriumphPay QuickPay',
    paymentReference: 'TP-9921448',
  },
];
